version: "3.9"
services:
  nginx:
    build: ./docker/nginx/
    ports:
      - 80:80

    volumes:
      - ./src/:/var/www/html/

  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - ./src/:/var/www/html/
    user: 1000:1000


  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password


volumes:
  postgres-data: