version: "3.9"
services:
  nginx:
    build: ./docker/nginx/
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./src/:/var/www/html/

  php:
    build: ./docker/php/
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - ./src/:/var/www/html/
    user: 1000:1000


  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    ports:
      - "5432:5432"


volumes:
  postgres-data:
